### PR TITLE
Dynamically updated badge-cell for the prize pool amount

### PR DESCRIPTION
**Pull request by nelsonjchen**
I built a service called https://cellshield.info/ that allows backing a shields.io badge with a cell from a public Google Spreadsheet and I'm curious if there's any interest in using this. Perhaps this might be useful to keep this part of the README updated?

### CODE REVIEW

**Comment by avivace** [comment]
This is quite cool! Thank you!

**Comment by nelsonjchen** [comment]
@avivace Feel free to use it in more places. I think I'll send another PR to update one more spot in the README.md with a dynamic value but I think you could use it as well at https://itch.io/jam/gbcompo21 assuming you are able to reference "external images".

**Comment by nelsonjchen** [comment]
@avivace 

It is possible to reference external images in the itch.io jam if you insert an image, go to the developer console in Chrome and change the img src attribute. You just can't do it from the UI.

**Comment by bbbbbr** [comment]
This is great. I updated itch.io - switching the description editor to html mode works for inserting the image tag (let me know if I didn't use the URL correctly).

**Comment by nelsonjchen** [comment]
@bbbbbr The URL is correct. Awesome!

The limitations are on shields.io side. If for some reason you want to do this:



then this is the URL to use. I just added `&color=green` to the end as mentioned in https://shields.io/endpoint .

https://shields.io/endpoint?url=https%3A%2F%2Fcellshield.info%2Fgs%3FspreadSheetId%3D196vIZGLbSk1ewzRnZc7Dy_LJdPQpfJUg-udT4iyBVOg%26cellRange%3DI11&color=green

**Comment by bbbbbr** [comment]
Thanks, green does look a little better. Updated. 

Going a little afield - Looks like it might support background transparency via RGBA? What's the syntax for that with `&color=`? I can get the RGB hex to work but not with the alpha component.

**Comment by nelsonjchen** [comment]
> Thanks, green does look a little better. Updated.
> 
> Going a little afield - Looks like it might support background transparency via RGBA? What's the syntax for that with `&color=`? I can get the RGB hex to work but not with the alpha component.

The syntax is like this:



https://shields.io/endpoint?url=https%3A%2F%2Fcellshield.info%2Fgs%3FspreadSheetId%3D196vIZGLbSk1ewzRnZc7Dy_LJdPQpfJUg-udT4iyBVOg%26cellRange%3DI11&color=rgba%28212%2C238%2C80%2C0.5%29

You have to encode that value of color for the `rgba()` syntax. 

FWIW, I like the current itch.io's badge's color and how it pops. Anyway, that's the syntax if you want to fiddle with that more.

**Comment by bbbbbr** [comment]
Thanks!

And yeah, agree that the current badge color looks good. My question had more to do with other scenarios where this might be useful. :)

**Pull request merged**
